/**
 * METEOASTUR LODE - Catálogo Oficial de Webcams de Asturias
 * Selección verificada de cámaras en tiempo real para playas, puertos y cumbres.
 * Enlaces contrastados y activos con HTTP 200 hacia los spots exactos.
 */

export const WEBCAMS_ASTURIAS = [
  // ==========================================
  // 🏖️ PLAYAS Y LITORAL CANTÁBRICO
  // ==========================================
  {
    id: 'salinas-central',
    category: 'playas',
    concejoId: 'castrillon',
    name: 'Playa de Salinas (Principal)',
    concejo: 'Castrillón',
    location: 'Salinas',
    desc: 'Vista panorámica del arenal, paseo marítimo y rompiente cantábrica',
    type: 'Surf y Baño',
    icon: '🏄‍♂️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/comarca-de-aviles/castrillon/salinas/playa-de-salinas-hd/26/'
  },
  {
    id: 'salinas-espartal',
    category: 'playas',
    concejoId: 'castrillon',
    name: 'Salinas - Rompiente El Espartal',
    concejo: 'Castrillón',
    location: 'Dunas de El Espartal',
    desc: 'Rompiente occidental de Salinas, zona de dunas y abrigo de San Juan',
    type: 'Surf Spot',
    icon: '🏄‍♂️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/comarca-aviles/castrillon/salinas/playa-de-salinas-el-espartal/170/'
  },
  {
    id: 'san-lorenzo-escalerona',
    category: 'playas',
    concejoId: 'gijon',
    name: 'San Lorenzo - La Escalerona',
    concejo: 'Gijón',
    location: 'Escalera 4',
    desc: 'Vista en directo de la Escalerona central, arenal y San Pedro',
    type: 'Urbana y Surf',
    icon: '🏖️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/centro/gijon/gijon/la-escalerona-playa-de-san-lorenzo-hd/148/'
  },
  {
    id: 'san-lorenzo-tostaderu',
    category: 'playas',
    concejoId: 'gijon',
    name: 'San Lorenzo - El Tostaderu y Piles',
    concejo: 'Gijón',
    location: 'Rinconín / Río Piles',
    desc: 'Zona este del arenal, desembocadura del Piles y rompiente surfera',
    type: 'Surf y Olas',
    icon: '🏄‍♂️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/centro/gijon/gijon/playa-de-san-lorenzo-el-tostaderu-hd/133/'
  },
  {
    id: 'san-lorenzo-panoramica',
    category: 'playas',
    concejoId: 'gijon',
    name: 'San Lorenzo - Panorámica de la Bahía',
    concejo: 'Gijón',
    location: 'Muro de San Lorenzo',
    desc: 'Vista completa de la concha de San Lorenzo de este a oeste',
    type: 'Panorámica Costera',
    icon: '🌊',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/gijon/gijon/san-lorenzo/panoramica-playa-hd/198/'
  },
  {
    id: 'gijon-rinconin',
    category: 'playas',
    concejoId: 'gijon',
    name: 'Playa del Rinconín y Costa Este',
    concejo: 'Gijón',
    location: 'El Rinconín',
    desc: 'Senda costera hacia La Ñora, cala rocosa y mar cantábrico',
    type: 'Cala y Senda',
    icon: '🏖️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/centro/gijon/costa/el-rinconin-san-lorenzo-hd/126/'
  },
  {
    id: 'gijon-poniente',
    category: 'playas',
    concejoId: 'gijon',
    name: 'Playa de Poniente y Puerto Deportivo',
    concejo: 'Gijón',
    location: 'Poniente / Cuesta El Cholo',
    desc: 'Dársena deportiva de Fomento y ensenada protegida de Poniente',
    type: 'Aguas Calmas',
    icon: '⛵',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/centro/gijon/gijon/puerto-deportivo-poniente-hd/41/'
  },
  {
    id: 'xago',
    category: 'playas',
    concejoId: 'gozon',
    name: 'Playa de Xagó',
    concejo: 'Gozón',
    location: 'Cabo Peñas',
    desc: 'Gran arenal virgen abierto al Atlántico con oleaje continuo y dunas',
    type: 'Surf Salvaje',
    icon: '🌊',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/cabo-penas/gozon/xago/playa-de-xago-hd/118/'
  },
  {
    id: 'luanco-ribera',
    category: 'playas',
    concejoId: 'gozon',
    name: 'Luanco - Playa de La Ribera',
    concejo: 'Gozón',
    location: 'Luanco',
    desc: 'Playa urbana resguardada de Luanco frente a la Torre del Reloj',
    type: 'Mar de Abrigo',
    icon: '🏖️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/cabo-penas/gozon/luanco/playa-de-la-ribera-hd/24/'
  },
  {
    id: 'luanco-muelle',
    category: 'playas',
    concejoId: 'gozon',
    name: 'Luanco - Muelle Pesquero y Bahía',
    concejo: 'Gozón',
    location: 'Puerto de Luanco',
    desc: 'Actividad marinera tradicional en la bahía al socaire del Peñas',
    type: 'Puerto y Bahía',
    icon: '⛵',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/cabo-penas/gozon/luanco/muelle-de-luanco-hd/91/'
  },
  {
    id: 'candas-paseo',
    category: 'playas',
    concejoId: 'carreno',
    name: 'Candás - Paseo Marítimo y Playa',
    concejo: 'Carreño',
    location: 'Candás',
    desc: 'Bahía marinera de Candás, La Palmera y senda litoral hacia Perlora',
    type: 'Costera',
    icon: '🏖️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/cabo-penas/carreno/candas/paseo-maritimo-de-candas/23/'
  },
  {
    id: 'rodiles-barra',
    category: 'playas',
    concejoId: 'villaviciosa',
    name: 'Rodiles - Barra de Surf Mundial',
    concejo: 'Villaviciosa',
    location: 'Desembocadura Ría Villaviciosa',
    desc: 'La mítica ola tubular izquierda de Rodiles en la desembocadura de la ría',
    type: 'Surf Legendario',
    icon: '🏄‍♂️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/comarca-de-la-sidra/villaviciosa/rodiles/surf-barra-de-playa-de-rodiles-hd/44/'
  },
  {
    id: 'rodiles-playa',
    category: 'playas',
    concejoId: 'villaviciosa',
    name: 'Playa y Pinar de Rodiles',
    concejo: 'Villaviciosa',
    location: 'Reserva Natural Ría de Villaviciosa',
    desc: 'Arenal extenso, paseo de madera y frondoso pinar de eucaliptos',
    type: 'Arenal y Naturaleza',
    icon: '🌲',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/comarca-de-la-sidra/villaviciosa/rodiles/playa-de-rodiles-hd/120/'
  },
  {
    id: 'playa-espana',
    category: 'playas',
    concejoId: 'villaviciosa',
    name: 'Playa España',
    concejo: 'Villaviciosa',
    location: 'Quintes / Villaviciosa',
    desc: 'Arenal encajonado entre acantilados verticales con rompiente constante',
    type: 'Surf y Acantilados',
    icon: '🏄‍♂️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/comarca-de-la-sidra/villaviciosa/quintes/playa-espana-hd/164/'
  },
  {
    id: 'playa-la-nora',
    category: 'playas',
    concejoId: 'villaviciosa',
    name: 'Playa de La Ñora',
    concejo: 'Villaviciosa',
    location: 'Quintueles / Límite Gijón',
    desc: 'Pintoresca cala cantábrica con arena dorada y llamativa peña central',
    type: 'Cala Cantábrica',
    icon: '🏖️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/comarca-de-la-sidra/villaviciosa/villaviciosa/playa-de-la-nora-hd/104/'
  },
  {
    id: 'santa-marina',
    category: 'playas',
    concejoId: 'ribadesella',
    name: 'Playa de Santa Marina',
    concejo: 'Ribadesella',
    location: 'Ribadesella',
    desc: 'Elegante arenal señorial con palacetes de indianos y desembocadura del Sella',
    type: 'Playa Urbana y Surf',
    icon: '🏖️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/oriente/ribadesella/ribadesella/playa-de-santa-marina-hd/166/'
  },
  {
    id: 'vega',
    category: 'playas',
    concejoId: 'ribadesella',
    name: 'Playa de Vega (Monumento Natural)',
    concejo: 'Ribadesella',
    location: 'Vega',
    desc: 'Playa virgen abierta al norte con dunas fósiles y oleaje potente',
    type: 'Playa Virgen',
    icon: '🌊',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/oriente/ribadesella/vega/playa-de-vega-hd/132/'
  },
  {
    id: 'llanes-barro',
    category: 'playas',
    concejoId: 'llanes',
    name: 'Playa de Barro',
    concejo: 'Llanes',
    location: 'Barro / Llanes',
    desc: 'Preciosa concha protegida del viento con aguas cristalinas turquesas',
    type: 'Aguas Calmas',
    icon: '🏖️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/oriente-de-asturias/llanes/barro/playa-de-barro-hd/16/'
  },
  {
    id: 'llanes-palombina',
    category: 'playas',
    concejoId: 'llanes',
    name: 'Playa de La Palombina (Celorio)',
    concejo: 'Llanes',
    location: 'Celorio / Llanes',
    desc: 'Arenal familiar de Celorio con vistas a islotes calizos y mar en calma',
    type: 'Cala Turquesa',
    icon: '🏖️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/oriente/llanes/celorio/playa-palombina-hd/156/'
  },
  {
    id: 'llanes-andrin',
    category: 'playas',
    concejoId: 'llanes',
    name: 'Playa de Andrín',
    concejo: 'Llanes',
    location: 'Andrín / Llanes',
    desc: 'Arenal salvaje bajo los acantilados de La Boriza y Castro de las Gaviotas',
    type: 'Surf y Corrientes',
    icon: '🌊',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/oriente/llanes/andrin/playa-de-andrin-hd/187/'
  },
  {
    id: 'llanes-san-antolin',
    category: 'playas',
    concejoId: 'llanes',
    name: 'Playa de San Antolín de Bedón',
    concejo: 'Llanes',
    location: 'Naves / Llanes',
    desc: 'El arenal más extenso de Llanes, desembocadura del río Bedón y olas vivas',
    type: 'Surf Abierto',
    icon: '🏄‍♂️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/oriente/llanes/bedon/playa-de-san-antolin-hd/131/'
  },
  {
    id: 'aguilar',
    category: 'playas',
    concejoId: 'muros-de-nalon',
    name: 'Playa de Aguilar',
    concejo: 'Muros de Nalón',
    location: 'Aguilar',
    desc: 'Emblemático arenal de Muros de Nalón con la majestuosa Peña Castiellu',
    type: 'Baño y Paisaje',
    icon: '🏖️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/bajo-nalon/muros-de-nalon/aguilar/playa-de-aguilar-ii-hd/205/'
  },
  {
    id: 'los-quebrantos',
    category: 'playas',
    concejoId: 'soto-del-barco',
    name: 'Playa de Los Quebrantos',
    concejo: 'Soto del Barco',
    location: 'San Juan de La Arena',
    desc: 'Extenso arenal en la desembocadura del Nalón conectado con Playón de Bayas',
    type: 'Surf y Ría',
    icon: '🏄‍♂️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/bajo-nalon/soto-del-barco/san-juan-del-arena/playa-de-los-quebrantos-hd/149/'
  },
  {
    id: 'tapia',
    category: 'playas',
    concejoId: 'tapia-de-casariego',
    name: 'Tapia - Playa de Anguileiro (La Grande)',
    concejo: 'Tapia de Casariego',
    location: 'Tapia de Casariego',
    desc: 'Cuna del surf del occidente asturiano y sede del campeonato internacional',
    type: 'Surf Internacional',
    icon: '🏄‍♂️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/occidente/tapia-de-casariego/tapia-de-casariego/playa-de-tapia-anguileiro-o-la-grande-hd/114/'
  },
  {
    id: 'penarronda',
    category: 'playas',
    concejoId: 'castropol',
    name: 'Playa de Peñarronda (Monumento Natural)',
    concejo: 'Castropol',
    location: 'Barres / Santa Gadea',
    desc: 'Singular playa cantábrica con su icónico peñasco horadado en el centro',
    type: 'Espacio Protegido',
    icon: '🌊',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/oscos-eo/castropol/penarronda/playa-de-penarronda-hd/27/'
  },

  // ==========================================
  // 🏔️ PUERTOS DE MONTAÑA, CUMBRES Y ESQUÍ
  // ==========================================
  {
    id: 'pajares-cuitu-negru',
    category: 'montana',
    concejoId: 'lena',
    name: 'Valgrande-Pajares (Cuitu Negru - 1.850 m)',
    concejo: 'Lena',
    location: 'Cumbre de Pajares',
    desc: 'Cota máxima de la estación de esquí con vista panorámica a la Cordillera',
    type: 'Alta Montaña y Nieve',
    icon: '❄️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/estacion-valgrande-pajares/lena/pajares/ei-valgrande-pajares-cuitu-negro-cueto-negro-hd/9/'
  },
  {
    id: 'pajares-ubinas',
    category: 'montana',
    concejoId: 'lena',
    name: 'Valgrande-Pajares (Panorámica Ubiñas)',
    concejo: 'Lena',
    location: 'Cueto Negro',
    desc: 'Sensacional vista abierta hacia el Macizo de Ubiña y pistas altas',
    type: 'Panorámica Alpina',
    icon: '🏔️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/estacion-valgrande-pajares/lena/pajares/ei-valgrande-pajares-panoramica-cueto-negro-ubinas-hd/144/'
  },
  {
    id: 'pajares-branillin',
    category: 'montana',
    concejoId: 'lena',
    name: 'Valgrande-Pajares (Brañillín - Zona Baja)',
    concejo: 'Lena',
    location: 'Base de Brañillín (1.480 m)',
    desc: 'Base de la estación invernal, zona de telesilla y servicios',
    type: 'Estación Invernal',
    icon: '⛷️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/montana-central/lena/estacion-valgrande-pajares/zona-baja-hd/180/'
  },
  {
    id: 'san-isidro-raya',
    category: 'montana',
    concejoId: 'aller',
    name: 'San Isidro / Fuentes de Invierno (La Raya - 1.520 m)',
    concejo: 'Aller',
    location: 'Puerto de San Isidro',
    desc: 'Cámara en la divisoria del puerto entre Asturias y León, base de pistas',
    type: 'Puerto y Nieve',
    icon: '❄️',
    provider: 'Webcams de Asturias',
    url: 'https://www.webcamsdeasturias.com/asturias/montana-central/aller/san-isidro/la-raya-hd/203/'
  },
  {
    id: 'san-isidro-felechosa',
    category: 'montana',
    concejoId: 'aller',
    name: 'Felechosa y Valle Alto de Aller',
    concejo: 'Aller',
    location: 'Felechosa',
    desc: 'Panorámica del valle glaciar y subida hacia el Puerto de San Isidro',
    type: 'Valle de Montaña',
    icon: '🏔️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/montana-central/aller/felechosa/panoramica-san-isidro-felechosa-hd/105/'
  },
  {
    id: 'puerto-tarna',
    category: 'montana',
    concejoId: 'caso',
    name: 'Puerto de Tarna (1.490 m)',
    concejo: 'Caso',
    location: 'Alto de Tarna - Parque de Redes',
    desc: 'Paso de montaña de la AS-117 que conecta el Valle del Nalón con León',
    type: 'Paso de Montaña',
    icon: '🚗',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/valle-del-nalon/caso/tarna/puerto-de-tarna-hd/147/'
  },
  {
    id: 'puerto-cerredo',
    category: 'montana',
    concejoId: 'degana',
    name: 'Puerto de Cerredo (1.290 m)',
    concejo: 'Degaña',
    location: 'Cerredo / Zarréu',
    desc: 'Paso montañoso del suroccidente asturiano en la Cordillera Cantábrica',
    type: 'Puerto de Montaña',
    icon: '🏔️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/occidente/degana/panoramica-de-cerredo/cerredo-hd/76/'
  },
  {
    id: 'somiedo-pola',
    category: 'montana',
    concejoId: 'somiedo',
    name: 'Pola de Somiedo (Parque Natural)',
    concejo: 'Somiedo',
    location: 'Pola de Somiedo',
    desc: 'Centro neurálgico del Parque Natural y Reserva de la Biosfera de Somiedo',
    type: 'Parque Natural',
    icon: '🐻',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/camin-real-de-la-mesa/somiedo/somiedo/pola-de-somiedo-hd/113/'
  },
  {
    id: 'somiedo-caunedo',
    category: 'montana',
    concejoId: 'somiedo',
    name: 'Somiedo - Caunedo (Subida al Puerto)',
    concejo: 'Somiedo',
    location: 'Caunedo (Subida a La Farrapona y Puerto Somiedo)',
    desc: 'Entorno de brañas y pastos de montaña camino al alto del puerto',
    type: 'Ruta de Montaña',
    icon: '🏔️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/camin-real-de-la-mesa/somiedo/somiedo/somiedo-caunedo-hd/106/'
  },
  {
    id: 'lagos-covadonga',
    category: 'montana',
    concejoId: 'cangas-de-onis',
    name: 'Lagos de Covadonga (Lago Enol - 1.070 m)',
    concejo: 'Cangas de Onís',
    location: 'Parque Nacional Picos de Europa',
    desc: 'El majestuoso Lago Enol y las cumbres calizas del Macizo Occidental',
    type: 'Parque Nacional',
    icon: '🏞️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/oriente/cangas-de-onis/cangas-de-onis/lagos-de-covadonga-lago-enol-hd/159/'
  },
  {
    id: 'picu-urriellu-camarmena',
    category: 'montana',
    concejoId: 'cabrales',
    name: 'Picos de Europa - Picu Urriellu (Naranjo de Bulnes)',
    concejo: 'Cabrales',
    location: 'Mirador de Camarmeña',
    desc: 'Vista imponente a la cara oeste de la mítica cumbre caliza de 2.519 m',
    type: 'Alta Montaña Emblemática',
    icon: '🧗‍♂️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/picos-de-europa/cabrales/camarmena/picu-urriellu-naranjo-de-bulnes-hd/43/'
  },
  {
    id: 'refugio-urriellu-bulnes',
    category: 'montana',
    concejoId: 'cabrales',
    name: 'Picos de Europa - Bulnes y Macizo Central',
    concejo: 'Cabrales',
    location: 'Bulnes de Arriba (El Castillo)',
    desc: 'La aldea aislada de Bulnes bajo las paredes verticales del Macizo Central',
    type: 'Pueblo de Montaña',
    icon: '🏔️',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/picos-de-europa/cabrales/bulnes/refugio-del-urriellu/135/'
  },
  {
    id: 'sotres-pandebano',
    category: 'montana',
    concejoId: 'cabrales',
    name: 'Picos de Europa - Sotres y Pandébano',
    concejo: 'Cabrales',
    location: 'Sotres (1.050 m)',
    desc: 'El pueblo más alto de Asturias y puerta de entrada al Macizo Central',
    type: 'Pueblo Más Alto de Asturias',
    icon: '🧀',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/picos-de-europa/cabrales/sotres/sotres-pandebano/81/'
  },
  {
    id: 'vega-de-ario',
    category: 'montana',
    concejoId: 'cangas-de-onis',
    name: 'Picos de Europa - Vega de Ario (1.630 m)',
    concejo: 'Cangas de Onís',
    location: 'Refugio Marqués de Villaviciosa',
    desc: 'Balcón sobre la Garganta del Cares y vista frontal al Macizo Central',
    type: 'Refugio de Alta Montaña',
    icon: '⛺',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/oriente/cangas-de-onis/vega-de-ario/refugio-marques-villaviciosa-vega-ario/177/'
  },
  {
    id: 'ponga-tiatordos',
    category: 'montana',
    concejoId: 'ponga',
    name: 'Parque Natural de Ponga (San Juan de Beleño / Tiatordos)',
    concejo: 'Ponga',
    location: 'San Juan de Beleño',
    desc: 'Panorámica de los bosques ponguetos y la cumbre piramidal del Tiatordos',
    type: 'Parque Natural',
    icon: '🌲',
    provider: 'Webcams de Asturias',
    url: 'http://www.webcamsdeasturias.com/asturias/oriente/ponga/san-juan-de-beleno/san-juan-de-beleno-san-xuan-picu-tiatordos/90/'
  }
];
